<template>
  <img
    v-for="({ name }, index) in images"
    :key="index"
    :src="'src/assets/' + name"
    alt="Images Generated by AI"
  />
</template>

<script setup>
const images = [
  { name: "1.png" },
  { name: "2.png" },
  { name: "3.png" },
  { name: "4.png" },
  { name: "5.png" },
  { name: "6.png" },
  { name: "7.png" },
  { name: "8.png" },
  { name: "9.png" },
  { name: "10.png" },
];
</script>

<style scoped></style>
